$ErrorActionPreference = "Stop"

$repoPath = "/home/codex/OmniPortal"
$remoteScriptPath = "$repoPath/scripts/pi-backend-deploy.sh"

ssh pi "mkdir -p $repoPath/scripts"
ssh pi "mkdir -p $repoPath/apps/backend"
ssh pi "mkdir -p $repoPath/apps/frontend"
scp "D:\PWD\OmniPortal\docker-compose.yml" "pi:${repoPath}/docker-compose.yml"
scp "D:\PWD\OmniPortal\apps\backend\Dockerfile" "pi:${repoPath}/apps/backend/Dockerfile"
scp "D:\PWD\OmniPortal\apps\backend\requirements.txt" "pi:${repoPath}/apps/backend/requirements.txt"
scp "D:\PWD\OmniPortal\apps\backend\main.py" "pi:${repoPath}/apps/backend/main.py"
scp "D:\PWD\OmniPortal\apps\frontend\index.html" "pi:${repoPath}/apps/frontend/index.html"
scp "D:\PWD\OmniPortal\apps\frontend\client.html" "pi:${repoPath}/apps/frontend/client.html"
scp "D:\PWD\OmniPortal\apps\frontend\admin.html" "pi:${repoPath}/apps/frontend/admin.html"
scp "D:\PWD\OmniPortal\apps\frontend\app.js" "pi:${repoPath}/apps/frontend/app.js"
scp "D:\PWD\OmniPortal\apps\frontend\client.js" "pi:${repoPath}/apps/frontend/client.js"
scp "D:\PWD\OmniPortal\apps\frontend\admin.js" "pi:${repoPath}/apps/frontend/admin.js"
scp "D:\PWD\OmniPortal\apps\frontend\shared.js" "pi:${repoPath}/apps/frontend/shared.js"
scp "D:\PWD\OmniPortal\apps\frontend\styles.css" "pi:${repoPath}/apps/frontend/styles.css"
$scriptContent = Get-Content -Raw "D:\PWD\OmniPortal\scripts\pi-backend-deploy.sh"
$scriptContent | ssh pi "cat > $remoteScriptPath && tr -d '\r' < $remoteScriptPath > ${remoteScriptPath}.tmp && mv ${remoteScriptPath}.tmp $remoteScriptPath && chmod +x $remoteScriptPath"
ssh pi "SKIP_GIT_UPDATE=1 bash $remoteScriptPath $repoPath"
